export type { DocConfig, LayoutProps } from "./types"
export { ThemeProvider } from "./theme/ThemeProvider"
export { resolveLayout, layoutRegistry } from "./registry/layouts"
export { ClassicLayout } from "./layouts/classic"
export { MinimalLayout } from "./layouts/minimal"
export { createMdxComponents } from "./mdx"
export type { CreateMdxOptions, MdxComponents } from "./mdx/types"
